name: TownyMenu
version: ${project.version}
main: ${main.class}
api-version: 1.13
softdepend:
  - Towny
  - HeadDatabase
folia-supported: true
author: Cobrex | Original author Tolmikarc.
libraries:
  - org.openjdk.nashorn:nashorn-core:15.4

commands:
  nationmenu:
    description: Opens the nation level GUI menu
    aliases: nm
    permission-message: "You do not have permission to use this command!"
    default: true
  townmenu:
    description: Opens the town level GUI menu
    aliases: tm
    permission-message: "You do not have permission to use this command!"
    default: true
  plotmenu:
    description: Opens the plot level GUI menu
    aliases: plm
    permission-message: "You do not have permission to use this command!"
    default: true
  townmenu reload:
    description: Reloads the settings file
    default: op
  chunkview:
    description: View the boarders of the chunk you are standing in.
    aliases:
      - cv
      - chunkv
    permission: chunkview.view
    permission-message: "You do not have permission to use this command!"
    default: true
    usage: |-
      /chunkview - to view the chunk boarder.
  chunkviewparticle:
    description: View the boarders of the chunk you are standing in.
    aliases:
      - cvp
      - chunkvp
    permission: chunkviewparticle.view
    permission-message: "You do not have permission to use this command!"
    default: true
    usage: |-
      /chunkviewparticle - to view the chunk boarder.
permissions:
  nationmenu.view:
    description: Opens the nation level GUI
    default: true
  townmenu.view:
    description: Opens the town level GUI
    default: true
  plotmenu.view:
    description: Opens the plot level GUI
    default: true
  townmenu.reload:
    description: Reloads the settings file
    default: op
  townymenu.nation.use:
    description: OPens the nation lavel GUI
    default: false
  townymenu.town.use:
    description: Opens the town level GUI
    default: false
  chunkview.view:
    description: Allows use of /chunkview
    default: true
  chunkviewparticle.view:
    description: Allows use of /chunkviewparticle
    default: true
