package me.cobrex.townymenu.config;

import me.cobrex.townymenu.settings.Settings;

public enum ConfigNodes {

	PREFIX(
			"prefix",
			"&b&lTM &7// ",
			"",
			"",
			"##################################################################################",
			"# +----------------------------------------------------------------------------+ #",
			"# |                       Welcome to TownyMenu Config                          | #",
			"# |                                                                            | #",
			"# | For help and support please join my discord:                               | #",
			"# | at https://discord.gg/Sgc6hy9CCSBlock                                      | #",
			"# |                                                                            | #",
			"# | Issues and bugs, please report at:                                         | #",
			"# | at: https://github.com/cobrex1/TownyMenu/issues                            | #",
			"# |                                                                            | #",
			"# | If using HeadDatabase for icons, please use the format                     | #",
			"# | hdb-[number] eg hdb-34567                                                  | #",
			"# |                                                                            | #",
			"# | If using Skull Owner for icons, please use the format                      | #",
			"# | skull-owner: eg skull-owner:Notch                                          | #",
			"# |                                                                            | #",
			"# | If using Skull Texture for icons, please use the format                    | #",
			"# | skull-texture: eg                                                          | #",
			"# | skull-texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0         | #",
			"# |                                                                            | #",
			"# | For item names please use:                                                 | #",
			"# | https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html          | #",
			"# |                                                                            | #",
			"# +----------------------------------------------------------------------------+ #",
			"##################################################################################",
			"",
			"",
			"# The prefix for messages from the plugin"),
	COLOR_MODE(
			"color_mode",
			"MINIMESSAGE",
			 "",
			"# For your color code setting, you have the option to use:",
			"# LEGACY - &5, &6&l etc, or",
			"# MINIMESSAGE - <red>, <bold><red>, <gradient:red:blue>",
			"# HEX is also supported, in LEGACY use #ff0000, in MINIMESSAGE use <#ff0000>",
			"# Please note that MINISSAGE mode is backward compatible with LEGACY,",
			"# but not the other way round."),
	LOCALE(
			"locale",
			"en",
			"",
			"# The Language this plugin's messages will be run in.",
			"# The following translations are available: cs, de, en, es, fr, pl, pt, ru, tr, vi and zh.",
			"# More will follow!",
			"# Once chosen, please re-boot the server or reload plugin to generate the chosen language file,",
			"# it will then appear in the localization folder."),
	ECONOMY(
			"economy",
			true,
			"",
			"# Whether or not economy is enabled or disabled for TownyMenu corresponding",
			"# with it being enabled or disabled for Towny Advanced"),
	MONEY_SYMBOL(
			"money_symbol",
			"$",
			"",
			"# The symbol used in messages for money"),
	LOG_LAG(
			"log_lag_over_mills",
			100,
			"",
			"# How many milliseconds should an action take before the lag is logged to console"),
	CHUNK_VIEW(
			"chunk_view",
			"REDSTONE_TORCH",
			"",
			"# Item to use to display chunk boarders"),
	CHUNK_VIEW_PARTICLE(
			"chunk_view_partilce",
			"HAPPY_VILLAGER",
			"",
			"# Get Particle names from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html",
			"# Particle to use to display chunk boarders"),
	MENU_NEXT_PAGE_BUTTON(
			"menu_next_page_button",
			"",
			"",
			"# Move to next page in paginated menus"),
	MENU_NEXT_PAGE_BUTTON_ITEM(
			"menu_next_page_button.item",
			"ARROW"),
	MENU_NEXT_PAGE_BUTTON_CMD(
			"menu_next_page_button.custommodeldata",
			0),
	MENU_PREVIOUS_PAGE_BUTTON(
			"menu_previous_page_button",
			"",
			"",
			"# Move to previous page in paginated menus"),
	MENU_PREVIOUS_PAGE_BUTTON_ITEM(
			"menu_previous_page_button.item",
			"ARROW"),
	MENU_PREVIOUS_PAGE_BUTTON_CMD(
			"menu_previous_page_button.custommodeldata",
			0),
	BACK_BUTTON(
			"back_button",
			"",
			"",
			"# Back Button icon to linked menu"),
	BACK_BUTTON_ITEM(
			"back_button.item",
			"OAK_DOOR"),
	BACK_BUTTON_CMD(
			"back_button.custommodeldata",
			0),
	FILLER_JOIN_NATION_MENU(
			"filler_join_nation_menu",
			"",
			"",
			"#-----Filler Icons----- #",
			"# If you wish the filler to be empty, set the material to AIR",
			"# HDB icons cannot be used for fillers",
			""),
    FILLER_JOIN_NATION_MENU_ITEM(
			"filler_join_nation_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_JOIN_NATION_MENU_CMD(
			"filler_join_nation_menu.custommodeldata",
			0),
	FILLER_NATION_MAIN_MENU(
			"filler_nation_main_menu",
			"",
			""),
	FILLER_NATION_MAIN_MENU_ITEM(
			"filler_nation_main_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_NATION_MAIN_MENU_CMD(
			"filler_nation_main_menu.custommodeldata",
			0),
	FILLER_NATION_TOGGLE_MENU(
			"filler_nation_toggle_menu",
			"",
			""),
	FILLER_NATION_TOGGLE_ITEM(
			"filler_nation_toggle_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_NATION_TOGGLE_CMD(
			"filler_nation_toggle_menu.custommodeldata",
			0),
	FILLER_NATION_ECONOMY_MENU(
			"filler_nation_economy_menu",
			""),
	FILLER_NATION_ECONOMY_MENU_ITEM(
			"filler_nation_economy_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_NATION_ECONOMY_MENU_CMD(
			"filler_nation_economy_menu.custommodeldata",
			0),
	FILLER_NATION_SETTINGS_MENU(
			"filler_nation_settings_menu",
			"",
			""),
	FILLER_NATION_SETTINGS_ITEM(
			"filler_nation_settings_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_NATION_SETTINGS_CMD(
			"filler_nation_settings_menu.custommodeldata",
			0),
	FILLER_NATION_RESIDENT_LIST_MENU(
			"filler_nation_resident_list_menu",
			""),
	FILLER_NATION_RESIDENT_LIST_MENU_ITEM(
			"filler_nation_resident_list_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_NATION_RESIDENT_LIST_MENU_CMD(
			"filler_nation_resident_list_menu.custommodeldata",
			0),
	FILLER_NATION_EXTRA_INFO_MENU(
			"filler_nation_extra_info_menu",
			""),
	FILLER_NATION_EXTRA_INFO_MENU_ITEM(
			"filler_nation_extra_info_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_NATION_EXTRA_INFO_MENU_CMD(
			"filler_nation_extra_info_menu.custommodeldata",
			0),
	FILLER_JOIN_TOWN_MENU(
			"filler_join_town_menu",
			"",
			""),
	FILLER_JOIN_TOWN_MENU_ITEM(
			"filler_join_town_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_JOIN_TOWN_MENU_CMD(
			"filler_join_town_menu.custommodeldata",
			0),
	FILLER_TOWN_MENU(
			"filler_town_menu",
			""),
	FILLER_TOWN_MENU_ITEM(
			"filler_town_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_TOWN_MENU_CMD(
			"filler_town_menu.custommodeldata",
			0),
	FILLER_TOWN_TOGGLE_MENU(
			"filler_town_toggle_menu",
			""),
	FILLER_TOWN_TOGGLE_MENU_ITEM(
			"filler_town_toggle_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_TOWN_TOGGLE_MENU_CMD(
			"filler_town_toggle_menu.custommodeldata",
			0),
	FILLER_TOWN_PERMS_MENU(
			"filler_town_perms_menu",
			""),
	FILLER_TOWN_PERMS_MENU_ITEM(
			"filler_town_perms_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_TOWN_PERMS_MENU_CMD(
			"filler_town_perms_menu.custommodeldata",
			0),
	FILLER_TOWN_GENERAL_SETTINGS_MENU(
			"filler_town_general_settings_menu",
			""),
	FILLER_TOWN_GENERAL_SETTINGS_MENU_ITEM(
			"filler_town_general_settings_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_TOWN_GENERAL_SETTINGS_MENU_CMD(
			"filler_town_general_settings_menu.custommodeldata",
			0),
	FILLER_TOWN_ECONOMY_MENU(
			"filler_town_economy_menu",
			""),
	FILLER_TOWN_ECONOMY_MENU_ITEM(
			"filler_town_economy_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_TOWN_ECONOMY_MENU_CMD(
			"filler_town_economy_menu.custommodeldata",
			0),
	FILLER_TOWN_EXTRA_INFO_MENU(
			"filler_town_extra_info_menu",
			""),
	FILLER_TOWN_EXTRA_INFO_MENU_ITEM(
			"filler_town_extra_info_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_TOWN_EXTRA_INFO_MENU_CMD(
			"filler_town_extra_info_menu.custommodeldata",
			0),
	FILLER_RESIDENT_MENU(
			"filler_resident_menu",
			"",
			""),
	FILLER_RESIDENT_MENU_ITEM(
			"filler_resident_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_RESIDENT_MENU_CMD(
			"filler_resident_menu.custommodeldata",
			0),
	FILLER_PLOT_MENU(
			"filler_plot_menu",
			"",
			""),
	FILLER_PLOT_MENU_ITEM(
			"filler_plot_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_PLOT_MENU_CMD(
			"filler_plot_menu.custommodeldata",
			0),
	FILLER_PLOT_TOGGLE_MENU(
			"filler_plot_toggle_menu",
			""),
	FILLER_PLOT_TOGGLE_MENU_ITEM(
			"filler_plot_toggle_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_PLOT_TOGGLE_MENU_CMD(
			"filler_plot_toggle_menu.custommodeldata",
			0),
	FILLER_PLOT_PERMS_MENU(
			"filler_plot_perms_menu",
			""),
	FILLER_PLOT_PERMS_MENU_ITEM(
			"filler_plot_perms_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_PLOT_PERMS_MENU_CMD(
			"filler_plot_perms_menu.custommodeldata",
			0),
	FILLER_PLOT_ADMIN_MENU(
			"filler_plot_admin_menu",
			""),
	FILLER_PLOT_ADMIN_MENU_ITEM(
			"filler_plot_admin_menu.item",
			"GRAY_STAINED_GLASS_PANE"),
	FILLER_PLOT_ADMIN_MENU_CMD(
			"filler_plot_admin_menu.custommodeldata",
			0),

	FIND_NATION_MENU_SIZE(
			"find_nation_menu_size",
			9,
			"",
			"# ------------------------------------------------------------- #",
			"",
			"# -----Nation Menus Icons-----#",
			"",
			"# Non-nation menu"),
	FIND_NATION_BUTTON(
			"find_nation_button",
			""),
	FIND_NATION_BUTTON_SLOT(
			"find_nation_button.slot",
			2),
	FIND_NATION_BUTTON_ITEM(
			"find_nation_button.item",
			"SUNFLOWER"),
	FIND_NATION_BUTTON_CMD(
			"find_nation_button.custommodeldata",
			0),
	CREATE_NATION_BUTTON(
			"create_nation_button",
			"",
			""),
	CREATE_NATION_BUTTON_SLOT(
			"create_nation_button.slot",
			5),
	CREATE_NATION_BUTTON_ITEM(
			"create_nation_button.item",
			"PLAYER_HEAD"),
	CREATE_NATION_BUTTON_CMD(
			"create_nation_button.custommodeldata",
			0),

	NATION_MAIN_MENU_SIZE("nation_main_menu_size",
			27,
			"",
			"# -----Nation Main Menu-----#"),
	NATION_TOGGLE_BUTTON(
			"nation_toggle_button",
			"",
			""),
	NATION_TOGGLE_BUTTON_SLOT(
			"nation_toggle_button.slot",
			2),
	NATION_TOGGLE_BUTTON_ITEM(
			"nation_toggle_button.item",
			"LEVER"),
	NATION_TOGGLE_BUTTON_CMD(
			"nation_toggle_button.custommodeldata",
			0),
	NATION_TOWN_LIST_BUTTON(
			"nation_town_list_button",
			"",
			""),
	NATION_TOWN_LIST_BUTTON_SLOT(
			"nation_town_list_button.slot",
			4),
	NATION_TOWN_LIST_BUTTON_ITEM(
			"nation_town_list_button.item",
			"PLAYER_HEAD"),
	NATION_TOWN_LIST_BUTTON_CMD(
			"nation_town_list_button.custommodeldata",
			0),
	NATION_RESIDENT_MENU_BUTTON(
			"nation_resident_menu_button",
			"",
			""),
	NATION_RESIDENT_MENU_BUTTON_SLOT(
			"nation_resident_menu_button.slot",
			6),
	NATION_RESIDENT_MENU_BUTTON_ITEM(
			"nation_resident_menu_button.item",
			"BOOK"),
	NATION_RESIDENT_MENU_BUTTON_CMD(
			"nation_resident_menu_button.custommodeldata",
			0),
	NATION_ECONOMY_MENU_BUTTON(
			"nation_economy_menu_button",
			"",
			""),
	NATION_ECONOMY_MENU_BUTTON_SLOT(
			"nation_economy_menu_button.slot",
			13),
	NATION_ECONOMY_MENU_BUTTON_ITEM(
			"nation_economy_menu_button.item",
			"EMERALD_BLOCK"),
	NATION_ECONOMY_MENU_BUTTON_CMD(
			"nation_economy_menu_button.custommodeldata",
			0),
	NATION_SETTINGS_MENU_BUTTON(
			"nation_settings_menu_button",
			"",
			""),
	NATION_SETTINGS_MENU_BUTTON_SLOT(
			"nation_settings_menu_button.slot",
			20),
	NATION_SETTINGS_MENU_BUTTON_ITEM(
			"nation_settings_menu_button.item",
			"ENDER_CHEST"),
	NATION_SETTINGS_MENU_BUTTON_CMD(
			"nation_settings_menu_button.custommodeldata",
			0),
	NATION_INVITE_TOWN_BUTTON(
			"nation_invite_town_button",
			"",
			""),
	NATION_INVITE_TOWN_BUTTON_SLOT(
			"nation_invite_town_button.slot",
			22),
	NATION_INVITE_TOWN_BUTTON_ITEM(
			"nation_invite_town_button.item",
			"BELL"),
	NATION_INVITE_TOWN_BUTTON_CMD(
			"nation_invite_town_button.custommodeldata",
			0),
	NATION_EXTRA_INFO_BUTTON(
			"nation_extra_info_button",
			"",
			""),
	NATION_EXTRA_INFO_BUTTON_SLOT(
			"nation_extra_info_button.slot",
			24),
	NATION_EXTRA_INFO_BUTTON_ITEM(
			"nation_extra_info_button.item",
			"ENCHANTED_BOOK"),
	NATION_EXTRA_INFO_BUTTON_CMD(
			"nation_extra_info_button.custommodeldata",
			0),
	NATION_MAIN_MENU_INFO(
			"nation_menu_info",
			"",
			""),
	NATION_MAIN_MENU_INFO_SLOT(
			"nation_menu_info.slot",
			18),
	NATION_MAIN_MENU_INFO_ITEM(
			"nation_menu_info.item",
			"NETHER_STAR"),
	NATION_MAIN_MENU_INFO_BUTTON_CMD(
			"nation_menu_info.custommodeldata",
			0),

	NATION_ECONOMY_MENU_SIZE(
			"nation_economy_menu_size",
			18,
			"",
			"# -----Nation Economy Menu Icons-----#"),
	NATION_BALANCE_BUTTON(
			"nation_balance_button",
			"",
			""),
	NATION_BALANCE_BUTTON_SLOT(
			"nation_balance_button.slot",
			1),
	NATION_BALANCE_BUTTON_ITEM(
			"nation_balance_button.item",
			"GOLD_BLOCK"),
	NATION_BALANCE_BUTTON_CMD(
			"nation_balance_button.custommodeldata",
			0),
	NATION_DEPOSIT_BUTTON(
			"nation_deposit_button",
			"",
			""),
	NATION_DEPOSIT_BUTTON_SLOT(
			"nation_deposit_button.slot",
			3),
	NATION_DEPOSIT_BUTTON_ITEM(
			"nation_deposit_button.item",
			"CHEST"),
	NATION_DEPOSIT_BUTTON_CMD(
			"nation_deposit_button.custommodeldata",
			0),
	NATION_WITHDRAW_BUTTON(
			"nation_withdraw_button",
			"",
			""),
	NATION_WITHDRAW_BUTTON_SLOT(
			"nation_withdraw_button.slot",
			5),
	NATION_WITHDRAW_BUTTON_ITEM(
			"nation_withdraw_button.item",
			"ENDER_CHEST"),
	NATION_WITHDRAW_BUTTON_CMD(
			"nation_withdraw_button.custommodeldata",
			0),
	NATION_SET_TAX_BUTTON(
			"nation_set_tax_button",
			"",
			""),
	NATION_SET_TAX_BUTTON_SLOT(
			"nation_set_tax_button.slot",
			7),
	NATION_SET_TAX_BUTTON_ITEM(
			"nation_set_tax_button.item",
			"ARROW"),
	NATION_SET_TAX_BUTTON_CMD(
			"nation_set_tax_button.custommodeldata",
			0),
	NATION_ECONOMY_INFO(
			"nation_economy_info_button",
			"",
			""),
	NATION_ECONOMY_INFO_SLOT(
			"nation_economy_info_button.slot",
			9),
	NATION_ECONOMY_INFO_ITEM(
			"nation_menu_info.item",
			"NETHER_STAR"),
	NATION_ECONOMY_INFO_BUTTON_CMD(
			"nation_economy_info_button.custommodeldata",
			0),
	NATION_ECONOMY_BACK_BUTTON(
			"nation_economy_back_button",
			"",
			""),
	NATION_ECONOMY_BACK_BUTTON_SLOT(
			"nation_economy_back_button.slot",
			17),
	NATION_ECONOMY_BACK_BUTTON_ITEM(
			"nation_economy_back_button.item",
			"OAK_DOOR"),
	NATION_ECONOMY_BACK_BUTTON_CMD(
			"nation_economy_back_button.custommodeldata",
			0),

	NATION_TOWN_MENU_SIZE("nation_town_menu_size",
			9,
			"",
			"# -----Nation Town Menu Icons-----#"),
	NATION_TOWN_KICK_BUTTON(
			"nation_town_kick_button",
			"",
			""),
	NATION_TOWN_KICK_BUTTON_SLOT(
			"nation_town_kick_button.slot",
			4),
	NATION_TOWN_KICK_BUTTON_ITEM(
			"nation_town_kick_button.item",
			"REDSTONE_BLOCK"),
	NATION_TOWN_KICK_BUTTON_CMD(
			"nation_town_kick_button.custommodeldata",
			0),
	NATION_TOWN_MENU_BACK_BUTTON(
			"nation_town_menu_back_button",
			"",
			""),
	NATION_TOWN_MENU_BACK_BUTTON_SLOT(
			"nation_town_menu_back_button.slot",
			8),
	NATION_TOWN_MENU_BACK_BOTTON_ITEM(
			"nation_town_menu_back_button.item",
			"OAK_DOOR"),
	NATION_TOWN_MENU_BACK_BUTTON_CMD(
			"nation_town_menu_back_button.custommodeldata",
			0),
	NATION_TOWN_LIST_INFO_BUTTON(
			"nation_town_list_info_button",
			"",
			""),
	NATION_TOWN_LIST_INFO_BUTTON_SLOT(
			"nation_town_list_info_button.slot",
			-1),
	NATION_TOWN_LIST_INFO_BUTTON_ITEM(
			"nation_town_list_info_button.item",
			"NETHER_STAR"),
	NATION_TOWN_LIST_INFO_BUTTON_CMD(
			"nation_town_list_info_button.custommodeldata",
			0),

	NATION_RESIDENT_MENU_SIZE("nation_resident_menu_size",
			18,
			"",
			"# -----Nation Resident Menu Icons-----#"),
	NATION_RESIDENT_TITLE_BUTTON(
			"nation_resident_title_button",
			"",
			""),
	NATION_RESIDENT_TITLE_BUTTON_SLOT(
			"nation_resident_title_button.slot",
			2),
	NATION_RESIDENT_TITLE_BUTTON_ITEM(
			"nation_resident_title_button.item",
			"IRON_SWORD"),
	NATION_RESIDENT_TITLE_BUTTON_CMD(
			"nation_resident_title_button.custommodeldata",
			0),
	NATION_RESIDENT_RANK_BUTTON(
			"nation_resident_rank_button",
			"",
			""),
	NATION_RESIDENT_RANK_BUTTON_SLOT(
			"nation_resident_rank_button.slot",
			4),
	NATION_RESIDENT_RANK_BUTTON_ITEM(
			"nation_resident_rank_button.item",
			"IRON_SWORD"),
	NATION_RESIDENT_RANK_BUTTON_CMD(
			"nation_resident_rank_button.custommodeldata",
			0),
	NATION_RESIDENT_SET_KING_BUTTON(
			"nation_resident_set_king_button",
			"",
			""),
	NATION_RESIDENT_SET_KING_BUTTON_SLOT(
			"nation_resident_set_king_button.slot",
			6),
	NATION_RESIDENT_SET_KING_BUTTON_ITEM(
			"nation_resident_set_king_button.item",
			"GOLDEN_APPLE"),
	NATION_RESIDENT_SET_KING_BUTTON_CMD(
			"nation_resident_set_king_button.custommodeldata",
			0),
	NATION_RESIDENT_MENU_INFO_BUTTON(
			"nation_resident_menu_info_button",
			"",
			""),
	NATION_RESIDENT_MENU_INFO_BUTTON_SLOT(
			"nation_resident_menu_info_button.slot",
			9),
	NATION_RESIDENT_MENU_INFO_BUTTON_ITEM(
			"nation_resident_menu_info_button.item",
			"NETHER_STAR"),
	NATION_RESIDENT_MENU_INFO_BUTTON_CMD(
			"nation_resident_menu_info_button.custommodeldata",
			0),
	NATION_RESIDENT_MENU_BACK_BUTTON(
			"nation_resident_menu_back_button",
			"",
			""),
	NATION_RESIDENT_MENU_BACK_BUTTON_SLOT(
			"nation_resident_menu_back_button.slot",
			17),
	NATION_RESIDENT_MENU_BACK_BUTTON_ITEM(
			"nation_resident_menu_back_button.item",
			"OAK_DOOR"),
	NATION_RESIDENT_BACK_BUTTON_CMD(
			"nation_resident_menu_back_button.custommodeldata",
			0),
	NATION_RESIDENT_LIST_INFO_BUTTON(
			"nation_resident_list_info_button",
			"",
			""),
	NATION_RESIDENT_LIST_INFO_BUTTON_SLOT(
			"nation_resident_list_info_button.slot",
			-1),
	NATION_RESIDENT_LIST_INFO_BUTTON_ITEM(
			"nation_resident_list_info_button.item",
			"NETHER_STAR"),
	NATION_RESIDENT_LIST_INFO_BUTTON_CMD(
			"nation_resident_list_info_button.custommodeldata",
			0),

	NATION_TOGGLE_MENU_SIZE("nation_toggle_menu_size",
			18,
			"",
			"# -----Toggle Nation Settings Menu Icons-----#"),
	NATION_TOGGLE_OPEN_BUTTON(
			"nation_toggle_open_button",
			"",
			""),
	NATION_TOGGLE_OPEN_BUTTON_SLOT(
			"nation_toggle_open_button.slot",
			2),
	NATION_TOGGLE_OPEN_BUTTON_ITEM(
			"nation_toggle_open_button.item",
			"ACACIA_DOOR"),
	NATION_TOGGLE_OPEN_BUTTON_CMD(
			"nation_toggle_open_button.custommodeldata",
			0),
	NATION_TOGGLE_PUBLIC_BUTTON(
			"nation_toggle_public_button",
			"",
			""),
	NATION_TOGGLE_PUBLIC_BUTTON_SLOT(
			"nation_toggle_public_button.slot",
			4),
	NATION_TOGGLE_PUBLIC_BUTTON_ITEM(
			"nation_toggle_public_button.item",
			"CHEST"),
	NATION_TOGGLE_PUBLIC_BUTTON_CMD(
			"nation_toggle_public_button.custommodeldata",
			0),
	NATION_TOGGLE_TAX_PERCENTAGE_BUTTON(
			"nation_toggle_tax_percentage_button",
			""),
	NATION_TOGGLE_TAX_PERCENTAGE_BUTTON_SLOT(
			"nation_toggle_tax_percentage_button.slot",
			6),
	NATION_TOGGLE_TAX_PERCENTAGE_BUTTON_ITEM(
			"nation_toggle_tax_percentage_button.item",
			"EMERALD"),
	NATION_TOGGLE_TAX_PERCENTAGE_BUTTON_CMD(
			"nation_toggle_tax_percentage_button.custommodeldata",
			0),
	NATION_TOGGLE_NEUTRAL_BUTTON(
			"nation_toggle_neutral_button",
			"",
			""),
	NATION_TOGGLE_NEUTRAL_BUTTON_SLOT(
			"nation_toggle_neutral_button.slot",
			12),
	NATION_TOGGLE_NEUTRAL_BUTTON_ITEM(
			"nation_toggle_neutral_button.item",
			"GRAY_DYE"),
	NATION_TOGGLE_NEUTRAL_BUTTON_CMD(
			"nation_toggle_neutral_button.custommodeldata",
			0),
	NATION_TOGGLE_PEACEFUL_BUTTON(
			"nation_toggle_peaceful_button",
			"",
			""),
	NATION_TOGGLE_PEACEFUL_BUTTON_SLOT(
			"nation_toggle_peaceful_button.slot",
			14),
	NATION_TOGGLE_PEACEFUL_BUTTON_ITEM(
			"nation_toggle_peaceful_button.item",
			"PAPER"),
	NATION_TOGGLE_PEACEFUL_BUTTON_CMD(
			"nation_toggle_peaceful_button.custommodeldata",
			0),
	NATION_TOGGLE_INFO_BUTTON(
			"nation_toggle_menu_info_button",
			"",
			""),
	NATION_TOGGLE_INFO_BUTTON_SLOT(
			"nation_toggle_menu_info_button.slot",
			9),
	NATION_TOGGLE_INFO_BUTTON_ITEM(
			"nation_toggle_menu_info_button.item",
			"NETHER_STAR"),
	NATION_TOGGLE_INFO_BUTTON_CMD(
			"nation_toggle_menu_info_button.custommodeldata",
			0),
	NATION_TOGGLE_MENU_BACK_BUTTON(
			"nation_toggle_menu_back_button",
			"",
			""),
	NATION_TOGGLE_MENU_BACK_BUTTON_SLOT(
			"nation_toggle_menu_back_button.slot",
			17),
	NATION_TOGGLE_MENU_BACK_BUTTON_ITEM(
			"nation_toggle_menu_back_button.item",
			"OAK_DOOR"),
	NATION_TOGGLE_BACK_BUTTON_CMD(
			"nation_toggle_menu_back_button.custommodeldata",
			0),

	NATION_SETTINGS_MENU_SIZE("nation_settings_menu_size",
			18,
			"",
			"# -----General Nation Settings Menu Icons-----#"),
	NATION_SET_SPAWN_BUTTON(
			"nation_set_spawn_button",
			"",
			""),
	NATION_SET_SPAWN_BUTTON_SLOT(
			"nation_set_spawn_button.slot",
			2),
	NATION_SET_SPAWN_BUTTON_ITEM(
			"nation_set_spawn_button.item",
			"GLOWSTONE"),
	NATION_SET_SPAWN_BUTTON_CMD(
			"nation_set_spawn_button.custommodeldata",
			0),
	NATION_SET_NAME_BUTTON(
			"nation_set_name_button",
			"",
			""),
	NATION_SET_NAME_BUTTON_SLOT(
			"nation_set_name_button.slot",
			4),
	NATION_SET_NAME_BUTTON_ITEM(
			"nation_set_name_button.item",
			"NAME_TAG"),
	NATION_SET_NAME_BUTTON_CMD(
			"nation_set_name_button.custommodeldata",
			0),
	NATION_SET_BOARD_BUTTON(
			"nation_set_board_button",
			"",
			""),
	NATION_SET_BOARD_BUTTON_SLOT(
			"nation_set_board_button.slot",
			6),
	NATION_SET_BOARD_BUTTON_ITEM(
			"nation_set_board_button.item",
			"OAK_SIGN"),
	NATION_SET_BOARD_BUTTON_CMD(
			"nation_set_board_button.custommodeldata",
			0),
	NATION_SETTINGS_INFO_BUTTON(
			"nation_settings_info_button",
			"",
			""),
	NATION_SETTINGS_INFO_BUTTON_SLOT(
			"nation_settings_info_button.slot",
			9),
	NATION_SETTINGS_INFO_BUTTON_ITEM(
			"nation_settings_info_button.item",
			"NETHER_STAR"),
	NATION_SETTINGS_INFO_BUTTON_CMD(
			"nation_settings_info_button.custommodeldata",
			0),
	NATION_SETTINGS_MENU_BACK_BUTTON(
			"nation_settings_menu_back_button",
			"",
			""),
	NATION_SETTINGS_MENU_BACK_BUTTON_SLOT(
			"nation_settings_menu_back_button.slot",
			17),
	NATION_SETTINGS_MENU_BACK_BUTTON_ITEM(
			"nation_settings_menu_back_button.item",
			"OAK_DOOR"),
	NATION_SETTINGS_BACK_BUTTON_CMD(
			"nation_settings_menu_back_button.custommodeldata",
			0),

	NATION_EXTRA_INFO_MENU_SIZE(
			"nation_extra_info_menu_size",
			9,
			"",
			"# -----Extra Nation Commands Info-----#"),
	NATION_EXTRA_COMMANDS_1_BUTTON(
			"nation_extra_commands_1_button",
			"",
			""),
	NATION_EXTRA_COMMANDS_1_BUTTON_SLOT(
			"nation_extra_commands_1_button.slot",
			3),
	NATION_EXTRA_COMMANDS_1_BUTTON_ITEM(
			"nation_extra_commands_1_button.item",
			"BOOK"),
	NATION_EXTRA_COMMANDS_1_BUTTON_CMD(
			"nation_extra_commands_1_button.custommodeldata",
			0),
	NATION_EXTRA_COMMANDS_2_BUTTON(
			"nation_extra_commands_2_button",
			"",
			""),
	NATION_EXTRA_COMMANDS_2_BUTTON_SLOT(
			"nation_extra_commands_2_button.slot",
			5),
	NATION_EXTRA_COMMANDS_2_BUTTON_ITEM(
			"nation_extra_commands_2_button.item",
			"CHEST"),
	NATION_EXTRA_COMMANDS_2_BUTTON_CMD(
			"nation_extra_commands_2_button.custommodeldata",
			0),
	NATION_EXTRA_MENU_BACK_BUTTON(
			"nation_extra_info_menu_back_button",
			"",
			""),
	NATION_EXTRA_MENU_BACK_BUTTON_SLOT(
			"nation_extra_info_menu_back_button.slot",
			8),
	NATION_EXTRA_MENU_BACK_BUTTON_ITEM(
			"nation_extra_info_menu_back_button.item",
			"OAK_DOOR"),
	NATION_EXTRA_MENU_BACK_BUTTON_CMD(
			"nation_extra_info_menu_back_button.custommodeldata",
			0),

	FIND_TOWN_MENU_SIZE("find_town_menu_size",
			9,
			"",
			"# ------------------------------------------------------------- #",
			"",
			"# -----Town Menu Icons-----#",
			"",
			"# Non-town menu"),
	FIND_TOWN_BUTTON(
			"find_town_button",
			"",
			""),
	FIND_TOWN_BUTTON_SLOT(
			"find_town_button.slot",
			3),
	FIND_TOWN_BUTTON_ITEM(
			"find_town_button.item",
			"SUNFLOWER"),
	FIND_TOWN_BUTTON_CMD(
			"find_town_button.custommodeldata",
			0),
	CREATE_TOWN_BUTTON(
			"create_town_button",
			"",
			""),
	CREATE_TOWN_BUTTON_SLOT(
			"create_town_button.slot",
			5),
	CREATE_TOWN_BUTTON_ITEM(
			"create_town_button.item",
			"PLAYER_HEAD"),
	CREATE_TOWN_BUTTON_CMD(
			"create_town_button.custommodeldata",
			0),

	TOWN_MAIN_MENU_SIZE("town_main_menu_size",
			27,
			"",
			"# -----Town Main Menu-----#"),
	TOWN_TOGGLE_BUTTON(
			"town_toggle_button",
			"",
			""),
	TOWN_TOGGLE_BUTTON_SLOT(
			"town_toggle_button.slot",
			2),
	TOWN_TOGGLE_BUTTON_ITEM(
			"town_toggle_button.item",
			"LEVER"),
	TOWN_TOGGLE_BUTTON_CMD(
			"town_toggle_button.custommodeldata",
			0),

	TOWN_RESIDENT_LIST_BUTTON(
			"town_resident_list_button",
			"",
			""),
	TOWN_RESIDENT_LIST_BUTTON_SLOT(
			"town_resident_list_button.slot",
			4),
	TOWN_RESIDENT_LIST_BUTTON_ITEM(
			"town_resident_list_button.item",
			"PLAYER_HEAD"),
	TOWN_RESIDENT_LIST_BUTTON_CMD(
			"town_resident_list_button.custommodeldata",
			0),
	TOWN_PERMISSIONS_MENU_BUTTON(
			"town_permissions_menu_button",
			"",
			""),
	TOWN_PERMISSIONS_MENU_BUTTON_SLOT(
			"town_permissions_menu_button.slot",
			6),
	TOWN_PERMISSIONS_MENU_BUTTON_ITEM(
			"town_permissions_menu_button.item",
			"STONE_AXE"),
	TOWN_PERMISSIONS_MENU_BUTTON_CMD(
			"town_permissions_menu_button.custommodeldata",
			0),
	TOWN_SETTINGS_MENU_BUTTON(
			"town_settings_menu_button",
			"",
			""),
	TOWN_SETTINGS_MENU_BUTTON_SLOT(
			"town_settings_menu_button.slot",
			11),
	TOWN_SETTINGS_MENU_BUTTON_ITEM(
			"town_settings_menu_button.item",
			"ENDER_CHEST"),
	TOWN_SETTINGS_MENU_BUTTON_CMD(
			"town_settings_menu_button.custommodeldata",
			0),
	TOWN_ECONOMY_MENU_BUTTON(
			"town_economy_menu_button",
			"",
			""),
	TOWN_ECONOMY_MENU_BUTTON_SLOT(
			"town_economy_menu_button.slot",
			13),
	TOWN_ECONOMY_MENU_BUTTON_ITEM(
			"town_economy_menu_button.item",
			"EMERALD_BLOCK"),
	TOWN_ECONOMY_MENU_BUTTON_CMD(
			"town_economy_menu_button.custommodeldata",
			0),
	TOWN_INVITE_MENU_BUTTON(
			"town_invite_menu_button",
			"",
			""),
	TOWN_INVITE_MENU_BUTTON_SLOT(
			"town_invite_menu_button.slot",
			15),
	TOWN_INVITE_MENU_BUTTON_ITEM(
			"town_invite_menu_button.item",
			"BELL"),
	TOWN_INVITE_MENU_BUTTON_CMD(
			"town_invite_menu_button.custommodeldata",
			0),
	TOWN_EXTRA_INFO_BUTTON(
			"town_extra_info_button",
			"",
			""),
	TOWN_EXTRA_INFO_BUTTON_SLOT(
			"town_extra_info_button.slot",
			21),
	TOWN_EXTRA_INFO_BUTTON_ITEM(
			"town_extra_info_button.item",
			"ENCHANTED_BOOK"),
	TOWN_EXTRA_INFO_BUTTON_CMD(
			"town_extra_info_button.custommodeldata",
			0),
	TOWN_PLOT_MENU_BUTTON(
			"town_plot_menu_button",
			"",
			""),
	TOWN_PLOT_MENU_BUTTON_SLOT(
			"town_plot_menu_button.slot",
			23),
	TOWN_PLOT_MENU_BUTTON_ITEM(
			"town_plot_menu_button.item",
			"WOODEN_SHOVEL"),
	TOWN_PLOT_MENU_BUTTON_CMD(
			"town_plot_menu_button.custommodeldata",
			0),
	TOWN_INFO_BUTTON(
			"town_info_button",
			"",
			""),
	TOWN_INFO_BUTTON_SLOT(
			"town_info_button.slot",
			18),
	TOWN_INFO_BUTTON_ITEM(
			"town_info_button.item",
			"NETHER_STAR"),
	TOWN_INFO_BUTTON_CMD(
			"town_info_button.custommodeldata",
			0),

	TOWN_TOGGLE_MENU_SIZE("town_toggle_menu_size",
			18,
			"",
			"# -----Toggle Town Settings Menu-----#"),
	TOWN_TOGGLE_FIRE_BUTTON(
			"town_toggle_fire_button",
			"",
			""),
	TOWN_TOGGLE_FIRE_BUTTON_SLOT(
			"town_toggle_fire_button.slot",
			1),
	TOWN_TOGGLE_FIRE_BUTTON_ITEM(
			"town_toggle_fire_button.item",
			"CAMPFIRE"),
	TOWN_TOGGLE_FIRE_BUTTON_CMD(
			"town_toggle_fire_button.custommodeldata",
			0),
	TOWN_TOGGLE_MOBS_BUTTON(
			"town_toggle_mobs_button",
			"",
			""),
	TOWN_TOGGLE_MOBS_BUTTON_SLOT(
			"town_toggle_mobs_button.slot",
			2),
	TOWN_TOGGLE_MOBS_BUTTON_ITEM(
			"town_toggle_mobs_button.item",
			"SHULKER_SPAWN_EGG"),
	TOWN_TOGGLE_MOBS_BUTTON_CMD(
			"town_toggle_mobs_button.custommodeldata",
			0),
	TOWN_TOGGLE_EXPLOSIONS_BUTTON(
			"town_toggle_explosions_button",
			"",
			""),
	TOWN_TOGGLE_EXPLOSIONS_BUTTON_SLOT(
			"town_toggle_explosions_button.slot",
			3),
	TOWN_TOGGLE_EXPLOSIONS_BUTTON_ITEM(
			"town_toggle_explosions_button.item",
			"TNT"),
	TOWN_TOGGLE_EXPLOSIONS_BUTTON_CMD(
			"town_toggle_explosions_button.custommodeldata",
			0),
	TOWN_TOGGLE_PVP_BUTTON(
			"town_toggle_pvp_button",
			"",
			""),
	TOWN_TOGGLE_PVP_BUTTON_SLOT(
			"town_toggle_pvp_button.slot",
			4),
	TOWN_TOGGLE_PVP_BUTTON_ITEM(
			"town_toggle_pvp_button.item",
			"GOLDEN_SWORD"),
	TOWN_TOGGLE_PVP_BUTTON_CMD(
			"town_toggle_pvp_button.custommodeldata",
			0),
	TOWN_TOGGLE_PUBLIC_BUTTON(
			"town_toggle_public_button",
			"",
			""),
	TOWN_TOGGLE_PUBLIC_BUTTON_SLOT(
			"town_toggle_public_button.slot",
			5),
	TOWN_TOGGLE_PUBLIC_BUTTON_ITEM(
			"town_toggle_public_button.item",
			"CHEST"),
	TOWN_TOGGLE_PUBLIC_BUTTON_CMD(
			"town_toggle_public_button.custommodeldata",
			0),
	TOWN_TOGGLE_OPEN_BUTTON(
			"town_toggle_open_button",
			"",
			""),
	TOWN_TOGGLE_OPEN_BUTTON_SLOT(
			"town_toggle_open_button.slot",
			6),
	TOWN_TOGGLE_OPEN_BUTTON_ITEM(
			"town_toggle_open_button.item",
			"ACACIA_DOOR"),
	TOWN_TOGGLE_OPEN_BUTTON_CMD(
			"town_toggle_open_button.custommodeldata",
			0),
	TOWN_TOGGLE_TAX_PERCENT_BUTTON(
			"town_toggle_tax_percent_button",
			"",
			""),
	TOWN_TOGGLE_TAX_PERCENT_BUTTON_SLOT(
			"town_toggle_tax_percent_button.slot",
			7),
	TOWN_TOGGLE_TAX_PERCENT_BUTTON_ITEM(
			"town_toggle_tax_percent_button.item",
			"EMERALD"),
	TOWN_TOGGLE_TAX_PERCENT_BUTTON_CMD(
			"town_toggle_tax_percent_button.custommodeldata",
			0),
	TOWN_TOGGLE_MENU_INFO_BUTTON(
			"town_toggle_menu_info_button",
			"",
			""),
	TOWN_TOGGLE_MENU_INFO_BUTTON_SLOT(
			"town_toggle_menu_info_button.slot",
			9),
	TOWN_TOGGLE_MENU_INFO_BUTTON_ITEM(
			"town_toggle_menu_info_button.item",
			"NETHER_STAR"),
	TOWN_TOGGLE_MENU_INFO_BUTTON_CMD(
			"town_toggle_menu_info_button.custommodeldata",
			0),
	TOWN_TOGGLE_MENU_BACK_BUTTON(
			"town_toggle_menu_back_button",
			"",
			""),
	TOWN_TOGGLE_MENU_BACK_BUTTON_SLOT(
			"town_toggle_menu_back_button.slot",
			17),
	TOWN_TOGGLE_MENU_BACK_BUTTON_ITEM(
			"town_toggle_menu_back_button.item",
			"OAK_DOOR"),
	TOWN_TOGGLE_MENU_BACK_BUTTON_CMD(
			"town_toggle_menu_back_button.custommodeldata",
			0),

	RESIDENT_MENU_SIZE("resident_menu_size",
			18,
			"",
			"# -----Town Resident Menu Icons-----#"),
	RESIDENT_KICK_BUTTON(
			"resident_kick_button",
			"",
			""),
	RESIDENT_KICK_BUTTON_SLOT(
			"resident_kick_button.slot",
			1),
	RESIDENT_KICK_BUTTON_ITEM(
			"resident_kick_button.item",
			"REDSTONE_BLOCK"),
	RESIDENT_KICK_BUTTON_CMD(
			"resident_kick_button.custommodeldata",
			0),
	RESIDENT_TITLE_BUTTON(
			"resident_title_button",
			"",
			""),
	RESIDENT_TITLE_BUTTON_SLOT(
			"resident_title_button.slot",
			3),
	RESIDENT_TITLE_BUTTON_ITEM(
			"resident_title_button.item",
			"NAME_TAG"),
	RESIDENT_TITLE_BUTTON_CMD(
			"resident_title_button.custommodeldata",
			0),
	RESIDENT_RANK_BUTTON(
			"resident_rank_button",
			"",
			""),
	RESIDENT_RANK_BUTTON_SLOT(
			"resident_rank_button.slot",
			5),
	RESIDENT_RANK_BUTTON_ITEM(
			"resident_rank_button.item",
			"IRON_SWORD"),
	RESIDENT_RANK_BUTTON_CMD(
			"resident_rank_button.custommodeldata",
			0),
	RESIDENT_SET_MAYOR_BUTTON(
			"resident_set_mayor_button",
			"",
			""),
	RESIDENT_SET_MAYOR_BUTTON_SLOT(
			"resident_set_mayor_button.slot",
			7),
	RESIDENT_SET_MAYOR_BUTTON_ITEM(
			"resident_set_mayor_button.item",
			"GOLDEN_APPLE"),
	RESIDENT_SET_MAYOR_BUTTON_CMD(
			"resident_set_mayor_button.custommodeldata",
			0),
	RESIDENT_MENU_INFO_BUTTON(
			"resident_menu_info_button",
			"",
			""),
	RESIDENT_MENU_INFO_BUTTON_SLOT(
			"resident_menu_info_button.slot",
			9),
	RESIDENT_MENU_INFO_BUTTON_ITEM(
			"resident_menu_info_button.item",
			"NETHER_STAR"),
	RESIDENT_MENU_INFO_BUTTON_CMD(
			"resident_menu_info_button.custommodeldata",
			0),
	RESIDENT_MENU_BACK_BUTTON(
			"resident_menu_back_button",
			"",
			""),
	RESIDENT_MENU_BACK_BUTTON_SLOT(
			"resident_menu_back_button.slot",
			17),
	RESIDENT_MENU_BACK_BUTTON_ITEM(
			"resident_menu_back_button.item",
			"OAK_DOOR"),
	RESIDENT_MENU_BACK_BUTTON_CMD(
			"resident_menu_back_button.custommodeldata",
			0),

	TOWN_PERMISSIONS_MENU_SIZE("town_permissions_menu_size",
			54,
			"",
			"# -----Set Town Permissions Menu Icons-----#"),
	//Info Buttons
	BUILD_INFO(
			"build_info",
			"",
			""),
	BUILD_INFO_SLOT(
			"build_info.slot",
			10),
	BUILD_INFO_ITEM(
			"build_info.item",
			"BRICKS"),
	BUILD_INFO_CMD(
			"build_info.custommodeldata",
			0),
	BREAK_INFO(
			"break_info",
			"",
			""),
	BREAK_INFO_SLOT(
			"break_info.slot",
			19),
	BREAK_BUTTON_ITEM(
			"break_info.item",
			"GOLDEN_PICKAXE"),
	BREAK_INFO_CMD(
			"break_info.custommodeldata",
			0),
	ITEM_USE_INFO(
			"item_use_info",
			"",
			""),
	ITEM_USE_INFO_SLOT(
			"item_use_info.slot",
			28),
	ITEM_USE_INFO_ITEM(
			"item_use_info.item",
			"FLINT_AND_STEEL"),
	ITEM_USE_INFO_CMD(
			"item_use_infp.custommodeldata",
			0),
	SWITCH_INFO(
			"switch_info",
			"",
			""),
	SWITCH_INFO_SLOT(
			"switch_info.slot",
			37),
	SWITCH_INFO_ITEM(
			"switch_info.item",
			"LEVER"),
	SWITCH_INFO_CMD(
			"switch_info.custommodeldata",
			0),

	RESIDENT_BUILD_BUTTON(
			"resident_build_button",
			"",
			""),
	RESIDENT_BUILD_BUTTON_SLOT(
			"resident_build_button.slot",
			12),
	RESIDENT_BUILD_BUTTON_ITEM(
			"resident_build_button.item",
			"BELL"),
	RESIDENT_BUILD_BUTTON_CMD(
			"resident_build_button.custommodeldata",
			0),
	RESIDENT_BREAK_BUTTON(
			"resident_break_button",
			"",
			""),
	RESIDENT_BREAK_BUTTON_SLOT(
			"resident_break_button.slot",
			21),
	RESIDENT_BREAK_BUTTON_ITEM(
			"resident_break_button.item",
			"BELL"),
	RESIDENT_BREAK_BUTTON_CMD(
			"resident_break_button.custommodeldata",
			0),
	RESIDENT_ITEM_USE_BUTTON(
			"resident_item_use_button",
			"",
			""),
	RESIDENT_ITEM_USE_BUTTON_SLOT(
			"resident_item_use_button.slot",
			30),
	RESIDENT_ITEM_USE_BUTTON_ITEM(
			"resident_item_use_button.item",
			"BELL"),
	RESIDENT_ITEM_USE_BUTTON_CMD(
			"resident_item_use_button.custommodeldata",
			0),
	RESIDENT_SWITCH_BUTTON(
			"resident_switch_button",
			"",
			""),
	RESIDENT_SWITCH_BUTTON_SLOT(
			"resident_switch_button.slot",
			39),
	RESIDENT_SWITCH_BUTTON_ITEM(
			"resident_switch_button.item",
			"BELL"),
	RESIDENT_SWITCH_BUTTON_CMD(
			"resident_switch_button.custommodeldata",
			0),

	NATION_BUILD_BUTTON(
			"nation_build_button",
			"",
			""),
	NATION_BUILD_BUTTON_SLOT(
			"nation_build_button.slot",
			13),
	NATION_BUILD_BUTTON_ITEM(
			"nation_build_button.item",
			"CHAINMAIL_CHESTPLATE"),
	NATION_BUILD_BUTTON_CMD(
			"nation_build_button.custommodeldata",
			0),
	NATION_BREAK_BUTTON(
			"nation_break_button",
			"",
			""),
	NATION_BREAK_BUTTON_SLOT(
			"nation_break_button.slot",
			22),
	NATION_BREAK_BUTTON_ITEM(
			"nation_break_button.item",
			"CHAINMAIL_CHESTPLATE"),
	NATION_BREAK_BUTTON_CMD(
			"nation_break_button.custommodeldata",
			0),
	NATION_ITEM_USE_BUTTON(
			"nation_item_use_button",
			"",
			""),
	NATION_ITEM_USE_BUTTON_SLOT(
			"nation_item_use_button.slot",
			31),
	NATION_ITEM_USE_BUTTON_ITEM(
			"nation_item_use_button.item",
			"CHAINMAIL_CHESTPLATE"),
	NATION_ITEM_USE_BUTTON_CMD(
			"nation_item_use_button.custommodeldata",
			0),
	NATION_SWITCH_BUTTON(
			"nation_switch_button",
			"",
			""),
	NATION_SWITCH_BUTTON_SLOT(
			"nation_switch_button.slot",
			40),
	NATION_SWITCH_BUTTON_ITEM(
			"nation_switch_button.item",
			"CHAINMAIL_CHESTPLATE"),
	NATION_SWITCH_BUTTON_CMD(
			"nation_switch_button.custommodeldata",
			0),

	ALLY_BUILD_BUTTON(
			"ally_build_button",
			"",
			""),
	ALLY_BUILD_BUTTON_SLOT(
			"ally_build_button.slot",
			14),
	ALLY_BUILD_BUTTON_ITEM(
			"ally_build_button.item",
			"CARROT"),
	ALLY_BUILD_BUTTON_CMD(
			"ally_build_button.custommodeldata",
			0),
	ALLY_BREAK_BUTTON(
			"ally_break_button",
			"",
			""),
	ALLY_BREAK_BUTTON_SLOT(
			"ally_break_button.slot",
			23),
	ALLY_BREAK_BUTTON_ITEM(
			"ally_break_button.item",
			"CARROT"),
	ALLY_BREAK_BUTTON_CMD(
			"ally_break_button.custommodeldata",
			0),
	ALLY_ITEM_USE_BUTTON(
			"ally_item_use_button",
			"",
			""),
	ALLY_ITEM_USE_BUTTON_SLOT(
			"ally_item_use_button.slot",
			32),
	ALLY_ITEM_USE_BUTTON_ITEM(
			"ally_item_use_button.item",
			"CARROT"),
	ALLY_ITEM_USE_BUTTON_CMD(
			"ally_item_use_button.custommodeldata",
			0),
	ALLY_SWITCH_BUTTON(
			"ally_switch_button",
			"",
			""),
	ALLY_SWITCH_BUTTON_SLOT(
			"ally_switch_button.slot",
			41),
	ALLY_SWITCH_BUTTON_ITEM(
			"ally_switch_button.item",
			"CARROT"),
	ALLY_SWITCH_BUTTON_CMD(
			"ally_switch_button.custommodeldata",
			0),

	OUTSIDER_BUILD_BUTTON(
			"outsider_build_button",
			"",
			""),
	OUTSIDER_BUILD_BUTTON_SLOT(
			"outsider_build_button.slot",
			15),
	OUTSIDER_BUILD_BUTTON_ITEM(
			"outsider_build_button.item",
			"BONE"),
	OUTSIDER_BUILD_BUTTON_CMD(
			"outsider_build_button.custommodeldata",
			0),
	OUTSIDER_BREAK_BUTTON(
			"outsider_break_button",
			"",
			""),
	OUTSIDER_BREAK_BUTTON_SLOT(
			"outsider_break_button.slot",
			24),
	OUTSIDER_BREAK_BUTTON_ITEM(
			"outsider_break_button.item",
			"BONE"),
	OUTSIDER_BREAK_BUTTON_CMD(
			"outsider_break_button.custommodeldata",
			0),
	OUTSIDER_ITEM_USE_BUTTON(
			"outsider_item_use_button",
			"",
			""),
	OUTSIDER_ITEM_USE_BUTTON_SLOT(
			"outsider_item_use_button.slot",
			33),
	OUTSIDER_ITEM_USE_BUTTON_ITEM(
			"outsider_item_use_button.item",
			"BONE"),
	OUTSIDER_ITEM_USE_BUTTON_CMD(
			"outsider_item_use_button.custommodeldata",
			0),
	OUTSIDER_SWITCH_BUTTON(
			"outsider_switch_button",
			"",
			""),
	OUTSIDER_SWITCH_BUTTON_SLOT(
			"outsider_switch_button.slot",
			42),
	OUTSIDER_SWITCH_BUTTON_ITEM(
			"outsider_switch_button.item",
			"BONE"),
	OUTSIDER_SWITCH_BUTTON_CMD(
			"outsider_switch_button.custommodeldata",
			0),

	RESET_ALL_BUTTON(
			"reset_all_button",
			"",
			""),
	RESET_ALL_BUTTON_SLOT(
			"reset_all_button.slot",
			17),
	RESET_ALL_BUTTON_ITEM(
			"reset_all_button.item",
			"REDSTONE_BLOCK"),
	RESET_ALL_BUTTON_CMD(
			"reset_all_button.custommodeldata",
			0),
	ALL_ON_BUTTON(
			"all_on_button",
			"",
			""),
	ALL_ON_BUTTON_SLOT(
			"all_on_button.slot",
			26),
	ALL_ON_BUTTON_ITEM(
			"all_on_button.item",
			"EMERALD_BLOCK"),
	ALL_ON_BUTTON_CMD(
			"all_on_button.custommodeldata",
			0),
	RESET_TO_TOWN_PERMS_BUTTON(
			"reset_to_town_perms_button",
			"",
			""),
	RESET_TO_TOWN_PERMS_BUTTON_SLOT(
			"reset_to_town_perms_button.slot",
			35),
	RESET_TO_TOWN_PERMS_BUTTON_ITEM(
			"reset_to_town_perms_button.item",
			"DIAMOND_BLOCK"),
	RESET_TO_TOWN_PERMS_BUTTON_CMD(
			"reset_to_town_perms_button.custommodeldata",
			0),
	TOWN_PERMISSION_MENU_INFO_BUTTON(
			"town_permissions_menu_info_button",
			"",
			""),
	TOWN_PERMISSIONS_MENU_INFO_BUTTON_SLOT(
			"town_permissions_menu_info_button.slot",
			45),
	TOWN_PERMISSIONS_MENU_INFO_BUTTON_ITEM(
			"town_permissions_menu_info_button.item",
			"NETHER_STAR"),
	TOWN_PERMISSIONS_MENU_INFO_BUTTON_CMD(
			"town_permissions_menu_info_button.custommodeldata",
			0),
	TOWN_PERMISSIONS_MENU_BACK_BUTTON(
			"town_permissions_menu_back_button",
			"",
			""),
	TOWN_PERMISSIONS_MENU_BACK_BUTTON_SLOT(
			"town_permissions_menu_back_button.slot",
			53),
	TOWN_PERMISSIONS_MENU_BACK_BUTTON_ITEM(
			"town_permissions_menu_back_button.item",
			"OAK_DOOR"),
	TOWN_PERMISSIONS_MENU_BACK_BUTTON_CMD(
			"town_permissions_menu_back_button.custommodeldata",
			0),

	TOWN_ECONOMY_MENU_SIZE("town_economy_menu_size",
			18,
			"",
			"# -----Town Economy Menu Icons-----#"),
	TOWN_BALANCE_BUTTON(
			"town_balance_button",
			"",
			""),
	TOWN_BALANCE_BUTTON_SLOT(
			"town_balance_button.slot",
			1),
	TOWN_BALANCE_BUTTON_ITEM(
			"town_balance_button.item",
			"EMERALD_BLOCK"),
	TOWN_BALANCE_BUTTON_CMD(
			"town_balance_button.custommodeldata",
			0),
	TOWN_DEPOSIT_BUTTON(
			"town_deposit_button",
			"",
			""),
	TOWN_DEPOSIT_BUTTON_SLOT(
			"town_deposit_button.slot",
			3),
	TOWN_DEPOSIT_BUTTON_ITEM(
			"town_deposit_button.item",
			"CHEST"),
	TOWN_DEPOSIT_BUTTON_CMD(
			"town_deposit_button.custommodeldata",
			0),
	TOWN_WITHDRAW_BUTTON(
			"town_withdraw_button",
			"",
			""),
	TOWN_WITHDRAW_BUTTON_SLOT(
			"town_withdraw_button.slot",
			5),
	TOWN_WITHDRAW_BUTTON_ITEM(
			"town_withdraw_button.item",
			"ENDER_CHEST"),
	TOWN_WITHDRAW_BUTTON_CMD(
			"town_withdraw_button.custommodeldata",
			0),
	TOWN_SET_TAX_BUTTON(
			"town_set_tax_button",
			"",
			""),
	TOWN_SET_TAX_BUTTON_SLOT(
			"town_set_tax_button.slot",
			7),
	TOWN_SET_TAX_BUTTON_ITEM(
			"town_set_tax_button.item",
			"ARROW"),
	TOWN_SET_TAX_BUTTON_CMD(
			"town_set_tax_button.custommodeldata",
			0),
	TOWN_ECONOMY_MENU_INFO_BUTTON(
			"town_economy_menu_info_button",
			"",
			""),
	TOWN_ECONOMY_MENU_INFO_BUTTON_SLOT(
			"town_economy_menu_info_button.slot",
			9),
	TOWN_ECONOMY_MENU_INFO_BUTTON_ITEM(
			"town_economy_menu_info_button.item",
			"NETHER_STAR"),
	TOWN_ECONOMY_MENU_INFO_BUTTON_CMD(
			"town_economy_menu_info_button.custommodeldata",
			0),
	TOWN_ECONOMY_MENU_BACK_BUTTON(
			"town_economy_menu_back_button",
			"",
			""),
	TOWN_ECONOMY_MENU_BACK_BUTTON_SLOT(
			"town_economy_menu_back_button.slot",
			17),
	TOWN_ECONOMY_MENU_BACK_BUTTON_ITEM(
			"town_economy_menu_back_button.item",
			"OAK_DOOR"),
	TOWN_ECONOMY_MENU_BACK_BUTTON_CMD(
			"town_economy_menu_back_button.custommodeldata",
			0),

	TOWN_SETTINGS_MENU_SIZE("town_settings_menu_size",
			18,
			"",
			"# -----General Nation Settings Menu Icons-----#"),
	TOWN_SET_HOME_BLOCK_BUTTON(
			"town_set_home_block_button",
			"",
			""),
	TOWN_SET_HOME_BLOCK_BUTTON_SLOT(
			"town_set_home_block_button.slot",
			1),
	TOWN_SET_HOME_BLOCK_BUTTON_ITEM(
			"town_set_home_block_button.item",
			"GLOWSTONE"),
	TOWN_SET_HOME_BLOCK_BUTTON_CMD(
			"town_set_home_block_button.custommodeldata",
			0),
	TOWN_SET_SPAWN_BUTTON(
			"town_set_spawn_button",
			"",
			""),
	TOWN_SET_SPAWN_BUTTON_SLOT(
			"town_set_spawn_button.slot",
			3),
	TOWN_SET_SPAWN_BUTTON_ITEM(
			"town_set_spawn_button.item",
			"LAPIS_LAZULI"),
	TOWN_SET_SPAWN_BUTTON_CMD(
			"town_set_spawn_button.custommodeldata",
			0),
	TOWN_SET_NAME_BUTTON(
			"town_set_name_button",
			"",
			""),
	TOWN_SET_NAME_BUTTON_SLOT(
			"town_set_name_button.slot",
			5),
	TOWN_SET_NAME_BUTTON_ITEM(
			"town_set_name_button.item",
			"NAME_TAG"),
	TOWN_SET_NAME_BUTTON_CMD(
			"town_set_name.custommodeldata",
			0),
	TOWN_SET_BOARD_BUTTON(
			"town_set_board_button",
			"",
			""),
	TOWN_SET_BOARD_BUTTON_SLOT(
			"town_set_board_button.slot",
			7),
	TOWN_SET_BOARD_BUTTON_ITEM(
			"town_set_board_button.item",
			"OAK_SIGN"),
	TOWN_SET_BOARD_BUTTON_CMD(
			"town_set_board_button.custommodeldata",
			0),
	TOWN_SETTINGS_MENU_INFO_BUTTON(
			"town_settings_menu_info_button",
			"",
			""),
	TOWN_SETTINGS_MENU_INFO_BUTTON_SLOT(
			"town_settings_menu_info_button.slot",
			9),
	TOWN_SETTINGS_MENU_INFO_BUTTON_ITEM(
			"town_settings_menu_info_button.item",
			"NETHER_STAR"),
	TOWN_SETTINGS_MENU_INFO_BUTTON_CMD(
			"town_settings_menu_info_button.custommodeldata",
			0),
	TOWN_SETTINGS_MENU_BACK_BUTTON(
			"town_settings_menu_back_button",
			"",
			""),
	TOWN_SETTINGS_MENU_BACK_BUTTON_SLOT(
			"town_settings_menu_back_button.slot",
			17),
	TOWN_SETTINGS_MENU_BACK_BUTTON_ITEM(
			"town_settings_menu_back_button.item",
			"OAK_DOOR"),
	TOWN_SETTINGS_MENU_BACK_BUTTON_CMD(
			"town_settings_menu_back_button.custommodeldata",
			0),

	TOWN_EXTRA_INFO_MENU_SIZE("town_extra_menu_size",
			9,
			"",
			"# -----Extra Town Commands & Info-----#"),
	TOWN_CLAIM_INFO(
			"town_claim_info",
			"",
			""),
	TOWN_CLAIM_INFO_SLOT(
			"town_claim_info.slot",
			3),
	TOWN_CLAIM_INFO_ITEM(
			"town_claim_info.item",
			"GOLDEN_AXE"),
	TOWN_CLAIM_INFO_CMD(
			"town_claim_info.custommodeldata",
			0),
	TOWN_EXTRA_COMMANDS_INFO(
			"town_extra_commands_info",
			"",
			""),
	TOWN_EXTRA_COMMANDS_INFO_SLOT(
			"town_extra_commands_info.slot",
			5),
	TOWN_EXTRA_COMMANDS_INFO_ITEM(
			"town_extra_commands_info.item",
			"BOOKSHELF"),
	TOWN_EXTRA_COMMANDS_INFO_CMD(
			"town_extra_commands_info.custommodeldata",
			0),
	TOWN_EXTRA_INFO_MENU_BACK_BUTTON(
			"town_extra_info_menu_back_button",
			"",
			""),
	TOWN_EXTRA_INFO_MENU_BACK_BUTTON_SLOT(
			"town_extra_info_menu_back_button.slot",
			8),
	TOWN_EXTRA_INFO_MENU_BACK_BUTTON_ITEM(
			"town_extra_info_menu_back_button.item",
			"OAK_DOOR"),
	TOWN_EXTRA_INFO_MENU_BACK_BUTTON_CMD(
			"town_extra_info_menu_back_button.custommodeldata",
			0),

	PLOT_MENU_SIZE("plot_menu_size",
			18,
			"",
			"# ------------------------------------- #",
			"",
			"# -----Plot Menus-----#",
			"",
			"# Plot Menu Icons"),
	PLOT_TOGGLE_BUTTON(
			"plot_toggle_button",
			"",
			""),
	PLOT_TOGGLE_BUTTON_SLOT(
			"plot_toggle_menu_button.slot",
			1),
	PLOT_TOGGLE_BUTTON_ITEM(
			"plot_toggle_menu_button.item",
			"LEVER"),
	PLOT_TOGGLE_BUTTON_CMD(
			"plot_toggle_menu_button.custommodeldata",
			0),
	PLOT_PERMISSIONS_MENU_BUTTON(
			"plot_permissions_menu_button",
			"",
			""),
	PLOT_PERMISSIONS_MENU_BUTTON_SLOT(
			"plot_permissions_menu_button.slot",
			3),
	PLOT_PERMISSIONS_MENU_BUTTON_ITEM(
			"plot_permissions_menu_button.item",
			"STONE_AXE"),
	PLOT_PERMISSIONS_MENU_BUTTON_CMD(
			"plot_permissions_menu_button.custommodeldata",
			0),
	PLOT_ADMIN_MENU_BUTTON(
			"plot_admin_menu_button",
			"",
			""),
	PLOT_ADMIN_MENU_BUTTON_SLOT(
			"plot_admin_menu_button.slot",
			5),
	PLOT_ADMIN_MENU_BUTTON_ITEM(
			"plot_admin_menu_button.item",
			"BELL"),
	PLOT_ADMIN_MENU_BUTTON_CMD(
			"plot_admin_menu_button.custommodeldata",
			0),
	PLOT_FRIEND_MENU_BUTTON(
			"plot_friend_menu_button",
			"",
			""),
	PLOT_FRIEND_MENU_BUTTON_SLOT(
			"plot_friend_menu_button.slot",
			7),
	PLOT_FRIEND_MENU_BUTTON_ITEM(
			"plot_friend_menu_button.item",
			"ENDER_CHEST"),
	PLOT_FRIEND_MENU_BUTTON_CMD(
			"plot_friend_menu_button.custommodeldata",
			0),
	PLOT_MENU_INFO_BUTTON(
			"plot_menu_info_button",
			"",
			""),
	PLOT_MENU_INFO_BUTTON_SLOT(
			"plot_menu_info_button.slot",
			9),
	PLOT_MENU_INFO_BUTTON_ITEM(
			"plot_menu_info_button.item",
			"NETHER_STAR"),
	PLOT_MENU_INFO_BUTTON_CMD(
			"plot_menu_info_button.custommodeldata",
			0),
	PLOT_MENU_BACK_BUTTON(
			"plot_menu_back_button",
			"",
			""),
	PLOT_MENU_BACK_BUTTON_SLOT(
			"plot_menu_back_button.slot",
			17),
	PLOT_MENU_BACK_BUTTON_ITEM(
			"plot_menu_back_button.item",
			"OAK_DOOR"),
	PLOT_MENU_BACK_BUTTON_CMD(
			"plot_menu_back_button.custommodeldata",
			0),

	PLOT_TOGGLE_MENU_SIZE("plot_toggle_menu_size",
			18,
			"",
			"# -----Toggle Plot Settings Menu-----#"),
	PLOT_TOGGLE_FIRE_BUTTON(
			"plot_toggle_fire_button",
			"",
			""),
	PLOT_TOGGLE_FIRE_BUTTON_SLOT(
			"plot_toggle_fire_button.slot",
			1),
	PLOT_TOGGLE_FIRE_BUTTON_ITEM(
			"plot_toggle_fire_button.item",
			"CAMPFIRE"),
	PLOT_TOGGLE_FIRE_BUTTON_CMD(
			"plot_toggle_fire_button.custommodeldata",
			0),
	PLOT_TOGGLE_MOBS_BUTTON(
			"plot_toggle_mobs_button",
			"",
			""),
	PLOT_TOGGLE_MOBS_BUTTON_SLOT(
			"plot_toggle_mobs_button.slot",
			3),
	PLOT_TOGGLE_MOBS_BUTTON_ITEM(
			"plot_toggle_mobs_button.item",
			"SHULKER_SPAWN_EGG"),
	PLOT_TOGGLE_MOBS_BUTTON_CMD(
			"plot_toggle_mobs_button.custommodeldata",
			0),
	PLOT_TOGGLE_EXPLOSIONS_BUTTON(
			"plot_toggle_explosions_button",
			"",
			""),
	PLOT_TOGGLE_EXPLOSIONS_BUTTON_SLOT(
			"plot_toggle_explosions_button.slot",
			5),
	PLOT_TOGGLE_EXPLOSIONS_BUTTON_ITEM(
			"plot_toggle_explosions_button.item",
			"TNT"),
	PLOT_TOGGLE_EXPLOSIONS_BUTTON_CMD(
			"plot_toggle_explosions_button.custommodeldata",
			0),
	PLOT_TOGGLE_PVP_BUTTON(
			"plot_toggle_pvp_button",
			"",
			""),
	PLOT_TOGGLE_PVP_BUTTON_SLOT(
			"plot_toggle_pvp_button.slot",
			7),
	PLOT_TOGGLE_PVP_BUTTON_ITEM(
			"plot_toggle_pvp_button.item",
			"GOLDEN_SWORD"),
	PLOT_TOGGLE_PVP_BUTTON_CMD(
			"plot_toggle_pvp_button.custommodeldata",
			0),
	PLOT_TOGGLE_MENU_INFO_BUTTON(
			"plot_toggle_menu_info_button",
			"",
			""),
	PLOT_TOGGLE_MENU_INFO_BUTTON_SLOT(
			"plot_toggle_menu_info_button.slot",
			9),
	PLOT_TOGGLE_MENU_INFO_BUTTON_ITEM(
			"plot_toggle_menu_info_button.item",
			"NETHER_STAR"),
	PLOT_TOGGLE_MENU_INFO_BUTTON_CMD(
			"plot_toggle_menu_info_button.custommodeldata",
			0),
	PLOT_TOGGLE_MENU_BACK_BUTTON(
			"plot_toggle_menu_back_button",
			"",
			""),
	PLOT_TOGGLE_MENU_BACK_BUTTON_SLOT(
			"plot_toggle_menu_back_button.slot",
			17),
	PLOT_TOGGLE_MENU_BACK_BUTTON_ITEM(
			"plot_toggle_menu_back_button.item",
			"OAK_DOOR"),
	PLOT_TOGGLE_MENU_BACK_BUTTON_CMD(
			"plot_toggle_menu_back_button.custommodeldata",
			0),

	PLOT_PERMISSIONS_MENU_SIZE("plot_permissions_menu_size",
			54,
			"",
			"# -----Set Plot Permissions Menu-----#"),
	PLOT_BUILD_BUTTON(
			"plot_build_button",
			"",
			""),
	PLOT_BUILD_BUTTON_SLOT(
			"plot_build_button.slot",
			10),
	PLOT_BUILD_BUTTON_ITEM(
			"plot_build_button.item",
			"BRICKS"),
	PLOT_BUILD_BUTTON_CMD(
			"plot_build_button.custommodeldata",
			0),
	PLOT_BREAK_BUTTON(
			"plot_break_button",
			"",
			""),
	PLOT_BREAK_BUTTON_SLOT(
			"plot_break_button.slot",
			19),
	PLOT_BREAK_BUTTON_ITEM(
			"plot_break_button.item",
			"GOLDEN_PICKAXE"),
	PLOT_BREAK_BUTTON_CMD(
			"plot_break_button.custommodeldata",
			0),
	PLOT_ITEM_USE_BUTTON(
			"plot_item_use_button",
			"",
			""),
	PLOT_ITEM_USE_BUTTON_SLOT(
			"plot_item_use_button.slot",
			28),
	PLOT_ITEM_USE_BUTTON_ITEM(
			"plot_item_use_button.item",
			"FLINT_AND_STEEL"),
	PLOT_ITEM_USE_BUTTON_CMD(
			"plot_item_use_button.custommodeldata",
			0),
	PLOT_SWITCH_BUTTON(
			"plot_switch_button",
			"",
			""),
	PLOT_SWITCH_BUTTON_SLOT(
			"plot_switch_button.slot",
			37),
	PLOT_SWITCH_BUTTON_ITEM(
			"plot_switch_button.item",
			"LEVER"),
	PLOT_SWITCH_BUTTON_CMD(
			"plot_switch_button.custommodeldata",
			0),

	PLOT_RESIDENT_BUILD_BUTTON(
			"plot_resident_build_button",
			"",
			""),
	PLOT_RESIDENT_BUILD_BUTTON_SLOT(
			"plot_resident_build_button.slot",
			12),
	PLOT_RESIDENT_BUILD_BUTTON_ITEM(
			"plot_resident_build_button.item",
			"BELL"),
	PLOT_RESIDENT_BUILD_BUTTON_CMD(
			"plot_resident_build_button.custommodeldata",
			0),
	PLOT_RESIDENT_BREAK_BUTTON(
			"plot_resident_break_button",
			"",
			""),
	PLOT_RESIDENT_BREAK_BUTTON_SLOT(
			"plot_resident_break_button.slot",
			21),
	PLOT_RESIDENT_BREAK_BUTTON_ITEM(
			"plot_resident_break_button.item",
			"BELL"),
	PLOT_RESIDENT_BREAK_BUTTON_CMD(
			"plot_resident_break_button.custommodeldata",
			0),
	PLOT_RESIDENT_ITEM_USE_BUTTON(
			"plot_resident_item_use_button",
			"",
			""),
	PLOT_RESIDENT_ITEM_USE_BUTTON_SLOT(
			"plot_resident_item_use_button.slot",
			30),
	PLOT_RESIDENT_ITEM_USE_BUTTON_ITEM(
			"plot_resident_item_use_button.item",
			"BELL"),
	PLOT_RESIDENT_ITEM_USE_BUTTON_CMD(
			"plot_resident_item_use_button.custommodeldata",
			0),
	PLOT_RESIDENT_SWITCH_BUTTON(
			"plot_resident_switch_button",
			"",
			""),
	PLOT_RESIDENT_SWITCH_BUTTON_SLOT(
			"plot_resident_switch_button.slot",
			39),
	PLOT_RESIDENT_SWITCH_BUTTON_ITEM(
			"plot_resident_switch_button.item",
			"BELL"),
	PLOT_RESIDENT_SWITCH_BUTTON_CMD(
			"plot_resident_switch_button.custommodeldata",
			0),

	PLOT_NATION_BUILD_BUTTON(
			"plot_nation_build_button",
			"",
			""),
	PLOT_NATION_BUILD_BUTTON_SLOT(
			"plot_nation_build_button.slot",
			13),
	PLOT_NATION_BUILD_BUTTON_ITEM(
			"plot_nation_build_button.item",
			"CHAINMAIL_CHESTPLATE"),
	PLOT_NATION_BUILD_BUTTON_CMD(
			"plot_nation_build_button.custommodeldata",
			0),
	PLOT_NATION_BREAK_BUTTON(
			"plot_nation_break_button",
			"",
			""),
	PLOT_NATION_BREAK_BUTTON_SLOT(
			"plot_nation_break_button.slot",
			22),
	PLOT_NATION_BREAK_BUTTON_ITEM(
			"plot_nation_break_button.item",
			"CHAINMAIL_CHESTPLATE"),
	PLOT_NATION_BREAK_BUTTON_CMD(
			"plot_nation_break_button.custommodeldata",
			0),
	PLOT_NATION_ITEM_USE_BUTTON(
			"plot_nation_item_use_button",
			"",
			""),
	PLOT_NATION_ITEM_USE_BUTTON_SLOT(
			"plot_nation_item_use_button.slot",
			31),
	PLOT_NATION_ITEM_USE_BUTTON_ITEM(
			"plot_nation_item_use_button.item",
			"CHAINMAIL_CHESTPLATE"),
	PLOT_NATION_ITEM_USE_BUTTON_CMD(
			"plot_nation_item_use_button.custommodeldata",
			0),
	PLOT_NATION_SWITCH_BUTTON(
			"plot_nation_switch_button",
			"",
			""),
	PLOT_NATION_SWITCH_BUTTON_SLOT(
			"plot_nation_switch_button.slot",
			40),
	PLOT_NATION_SWITCH_BUTTON_ITEM(
			"plot_nation_switch_button.item",
			"CHAINMAIL_CHESTPLATE"),
	PLOT_NATION_SWITCH_BUTTON_CMD(
			"plot_nation_switch_button.custommodeldata",
			0),

	PLOT_ALLY_BUILD_BUTTON(
			"plot_ally_build_button",
			"",
			""),
	PLOT_ALLY_BUILD_BUTTON_SLOT(
			"plot_ally_build_button.slot",
			14),
	PLOT_ALLY_BUILD_BUTTON_ITEM(
			"plot_ally_build_button.item",
			"CARROT"),
	PLOT_ALLY_BUILD_BUTTON_CMD(
			"plot_ally_build_button.custommodeldata",
			0),
	PLOT_ALLY_BREAK_BUTTON(
			"plot_ally_break_button",
			"",
			""),
	PLOT_ALLY_BREAK_BUTTON_SLOT(
			"plot_ally_break_button.slot",
			23),
	PLOT_ALLY_BREAK_BUTTON_ITEM(
			"plot_ally_break_button.item",
			"CARROT"),
	PLOT_ALLY_BREAK_BUTTON_CMD(
			"plot_ally_break_button.custommodeldata",
			0),
	PLOT_ALLY_ITEM_USE_BUTTON(
			"plot_ally_item_use_button",
			"",
			""),
	PLOT_ALLY_ITEM_USE_BUTTON_SLOT(
			"plot_ally_item_use_button.slot",
			32),
	PLOT_ALLY_ITEM_USE_BUTTON_ITEM(
			"plot_ally_item_use_button.item",
			"CARROT"),
	PLOT_ALLY_ITEM_USE_BUTTON_CMD(
			"plot_ally_item_use_button.custommodeldata",
			0),
	PLOT_ALLY_SWITCH_BUTTON(
			"plot_ally_switch_button",
			"",
			""),
	PLOT_ALLY_SWITCH_BUTTON_SLOT(
			"plot_ally_switch_button.slot",
			41),
	PLOT_ALLY_SWITCH_BUTTON_ITEM(
			"plot_ally_switch_button.item",
			"CARROT"),
	PLOT_ALLY_SWITCH_BUTTON_CMD(
			"plot_ally_switch_button.custommodeldata",
			0),

	PLOT_OUTSIDER_BUILD_BUTTON(
			"plot_outsider_build_button",
			"",
			""),
	PLOT_OUTSIDER_BUILD_BUTTON_SLOT(
			"plot_outsider_build_button.slot",
			15),
	PLOT_OUTSIDER_BUILD_BUTTON_ITEM(
			"plot_outsider_build_button.item",
			"BONE"),
	PLOT_OUTSIDER_BUILD_BUTTON_CMD(
			"plot_outsider_build_button.custommodeldata",
			0),
	PLOT_OUTSIDER_BREAK_BUTTON(
			"plot_outsider_break_button",
			"",
			""),
	PLOT_OUTSIDER_BREAK_BUTTON_SLOT(
			"plot_outsider_break_button.slot",
			24),
	PLOT_OUTSIDER_BREAK_BUTTON_ITEM(
			"plot_outsider_break_button.item",
			"BONE"),
	PLOT_OUTSIDER_BREAK_BUTTON_CMD(
			"plot_outsider_break_button.custommodeldata",
			0),
	PLOT_OUTSIDER_ITEM_USE_BUTTON(
			"plot_outsider_item_use_button",
			"",
			""),
	PLOT_OUTSIDER_ITEM_USE_BUTTON_SLOT(
			"plot_outsider_item_use_button.slot",
			33),
	PLOT_OUTSIDER_ITEM_USE_BUTTON_ITEM(
			"plot_outsider_item_use_button.item",
			"BONE"),
	PLOT_OUTSIDER_ITEM_USE_BUTTON_CMD(
			"plot_outsider_item_use_button.custommodeldata",
			0),
	PLOT_OUTSIDER_SWITCH_BUTTON(
			"plot_outsider_switch_button",
			"",
			""),
	PLOT_OUTSIDER_SWITCH_BUTTON_SLOT(
			"plot_outsider_switch_button.slot",
			42),
	PLOT_OUTSIDER_SWITCH_BUTTON_ITEM(
			"plot_outsider_switch_button.item",
			"BONE"),
	PLOT_OUTSIDER_SWITCH_BUTTON_CMD(
			"plot_outsider_switch_button.custommodeldata",
			0),

	PLOT_RESET_ALL_BUTTON(
			"plot_reset_all_button",
			"",
			""),
	PLOT_RESET_ALL_BUTTON_SLOT(
			"plot_reset_all_button.slot",
			26),
	PLOT_RESET_ALL_BUTTON_ITEM(
			"plot_reset_all_button.item",
			"REDSTONE_BLOCK"),
	PLOT_RESET_ALL_BUTTON_CMD(
			"plot_reset_all_button.custommodeldata",
			0),
	PLOT_ALL_ON_BUTTON(
			"plot_all_on_button",
			"",
			""),
	PLOT_ALL_ON_BUTTON_SLOT(
			"plot_all_on_button.slot",
			35),
	PLOT_ALL_ON_BUTTON_ITEM(
			"plot_all_on_button.item",
			"EMERALD_BLOCK"),
	PLOT_ALL_ON_BUTTON_CMD(
			"plot_all_on_button.custommodeldata",
			0),
	PLOT_PERMISSIONS_MENU_INFO(
			"plot_permissions_menu_info",
			"",
			""),
	PLOT_PERMISSIONS_MENU_INFO_SLOT(
			"plot_permissions_menu_info.slot",
			45),
	PLOT_PERMISSIONS_MENU_INFO_ITEM(
			"plot_permissions_menu_info.item",
			"NETHER_STAR"),
	PLOT_PERMISSIONS_MENU_INFO_CMD(
			"plot_permissions_menu_info.custommodeldata",
			0),
	PLOT_PERMISSIONS_MENU_BACK_BUTTON(
			"plot_permissions_menu_back_button",
			"",
			""),
	PLOT_PERMISSIONS_MENU_BACK_BUTTON_SLOT(
			"plot_permissions_menu_back_button.slot",
			53),
	PLOT_PERMISSIONS_MENU_BACK_BUTTON_ITEM(
			"plot_permissions_menu_back_button.item",
			"OAK_DOOR"),
	PLOT_PERMISSIONS_MENU_BACK_BUTTON_CMD(
			"plot_permissions_menu_back_button.custommodeldata",
			0),

	PLOT_ADMIN_MENU_SIZE("plot_admin_menu_size",
			18,
			"",
			"# -----Plot Admin Menu-----#"),
	PLOT_ADMIN_FOR_SALE_BUTTON(
			"plot_admin_for_sale_button",
			"",
			""),
	PLOT_ADMIN_FOR_SALE_BUTTON_SLOT(
			"plot_admin_for_sale_button.slot",
			1),
	PLOT_ADMIN_FOR_SALE_BUTTON_ITEM(
			"plot_admin_for_sale_button.item",
			"EMERALD_BLOCK"),
	PLOT_ADMIN_FOR_SALE_BUTTON_CMD(
			"plot_admin_for_sale_button.custommodeldata",
			0),
	PLOT_ADMIN_NOT_FOR_SALE_BUTTON(
			"plot_admin_not_for_sale_button",
			"",
			""),
	PLOT_ADMIN_NOT_FOR_SALE_BUTTON_SLOT(
			"plot_admin_not_for_sale_button.slot",
			3),
	PLOT_ADMIN_NOT_FOR_SALE_BUTTON_ITEM(
			"plot_admin_not_for_sale_button.item",
			"REDSTONE_BLOCK"),
	PLOT_ADMIN_NOT_FOR_SALE_BUTTON_CMD(
			"plot_admin_not_for_sale_button.custommodeldata",
			0),
	PLOT_ADMIN_SET_PLOT_TYPE_BUTTON(
			"plot_admin_set_plot_type_button",
			"",
			""),
	PLOT_ADMIN_SET_PLOT_TYPE_BUTTON_SLOT(
			"plot_admin_set_plot_type_button.slot",
			5),
	PLOT_ADMIN_SET_PLOT_TYPE_BUTTON_ITEM(
			"plot_admin_set_plot_type_button.item",
			"DARK_OAK_WOOD"),
	PLOT_ADMIN_SET_PLOT_TYPE_BUTTON_CMD(
			"plot_admin_set_plot_type_button.custommodeldata",
			0),
	PLOT_ADMIN_EVICT_RES_BUTTON(
			"plot_admin_evict_res_button",
			"",
			""),
	PLOT_ADMIN_EVICT_RES_BUTTON_SLOT(
			"plot_admin_evict_res_button.slot",
			7),
	PLOT_ADMIN_EVICT_RES_BUTTON_ITEM(
			"plot_admin_evict_res_button.item",
			"DIAMOND_AXE"),
	PLOT_ADMIN_EVICT_RES_BUTTON_CMD(
			"plot_admin_evict_res_button.custommodeldata",
			0),
	PLOT_ADMIN_MENU_INFO_BUTTON(
			"plot_admin_menu_info_button",
			"",
			""),
	PLOT_ADMIN_MENU_INFO_BUTTON_SLOT(
			"plot_admin_menu_info_button.slot",
			9),
	PLOT_ADMIN_MENU_INFO_BUTTON_ITEM(
			"plot_admin_menu_info_button.item",
			"NETHER_STAR"),
	PLOT_ADMIN_MENU_INFO_BUTTON_CMD(
			"plot_admin_menu_info_button.custommodeldata",
			0),
	PLOT_ADMIN_MENU_BACK_BUTTON(
			"plot_permissions_menu_back_button",
			"",
			""),
	PLOT_ADMIN_MENU_BACK_BUTTON_SLOT(
			"plot_admin_menu_back_button.slot",
			17),
	PLOT_ADMIN_MENU_BACK_BUTTON_ITEM(
			"plot_admin_menu_back_button.item",
			"OAK_DOOR"),
	PLOT_ADMIN_MENU_BACK_BUTTON_CMD(
			"plot_admin_menu_back_button.custommodeldata",
			0);

	private final String root;
	private final Object def;
	private final String[] comments;

	ConfigNodes(String root, Object def, String... comments) {
		this.root = root;
		this.def = def;
		this.comments = comments;
	}

	public String getRoot() {
		return root;
	}

	public Object getDefault() {
		return def;
	}

	public String[] getComments() {
		return this.comments;
	}

	public String getSub(String childKey) {
		return this.root + "." + childKey;
	}

	public String getPath() {
		return root;
	}

	public String getString() {
		Object val = Settings.getConfig().get(root);
		return val != null ? val.toString() : def.toString();
	}

	public int getInt() {
		Object val = Settings.getConfig().get(root);
		if (val instanceof Number n) return n.intValue();
		try {
			return Integer.parseInt(val.toString());
		} catch (Exception e) {
			return (def instanceof Number) ? ((Number) def).intValue() : 0;
		}
	}
}
